# See https://github.com/helm/chart-testing#configuration
chart-dirs: charts
check-version-increment: false
debug: true
helm-extra-args: '--timeout 900s'
remote: origin
target-branch: main
upgrade: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
