# See https://github.com/helm/chart-testing#configuration
chart-dirs: charts
check-version-increment: false
debug: true
remote: origin
target-branch: main
upgrade: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
