# See https://github.com/helm/chart-testing#configuration
chart-dirs: charts
check-version-increment: false
debug: false
remote: origin
target-branch: main
upgrade: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
chart-repos:
- opensearch=https://opensearch-project.github.io/helm-charts/
- elastic=https://helm.elastic.co
- minio=https://charts.min.io/
