sources:
  eck-stack:
    kind: helmchart
    spec:
      url: https://helm.elastic.co
      name: eck-stack
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: eck-stack
  minio:
    kind: helmchart
    spec:
      url: https://charts.min.io/
      name: minio
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: minio
  opensearch:
    kind: helmchart
    spec:
      url: https://opensearch-project.github.io/helm-charts/
      name: opensearch
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: opensearch
  dragonfly:
    kind: dockerimage
    spec:
      image: ghcr.io/dragonflydb/dragonfly/helm/dragonfly
      name: dragonfly
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: dragonfly
conditions: {}
targets:
  eck-stack:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/opencti/Chart.yaml
      key: $.dependencies[0].version
    sourceid: eck-stack
  minio:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/opencti/Chart.yaml
      key: $.dependencies[1].version
    sourceid: minio
  opensearch:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/opencti/Chart.yaml
      key: $.dependencies[2].version
    sourceid: opensearch
  dragonfly:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/opencti/Chart.yaml
      key: $.dependencies[4].version
    sourceid: dragonfly
