{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencti.fullname" $ }}-{{ .name }}
  labels:
    {{- include "opencti.serverLabels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{- if regexMatch "\n" $value }}
  {{ $key }}: |
    {{ $value | nindent 4 | trim }}
  {{- else }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
{{- end }}
