{{- if not .Values.clustering.enabled }}
{{- include "opencti.deploymentTemplate" (merge (dict "serverType" "server") .) }}
{{- else }}
{{- if .Values.clustering.frontend.enabled }}
---
{{ include "opencti.deploymentTemplate" (merge (dict "serverType" "frontend") .) }}
{{- end }}
{{- if .Values.clustering.ingestion.enabled }}
---
{{ include "opencti.deploymentTemplate" (merge (dict "serverType" "ingestion") .) }}
{{- end }}
{{- end }}
