{{- if not .Values.clustering.enabled }}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencti.fullname" . }}-server
  labels:
    {{- include "opencti.serverLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opencti.selectorServerLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- else }}
{{- if and .Values.clustering.frontend.enabled .Values.clustering.frontend.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencti.fullname" . }}-frontend
  labels:
    {{- include "opencti.frontendLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opencti.selectorFrontendLabels" . | nindent 6 }}
  {{- if .Values.clustering.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.clustering.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.clustering.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.clustering.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- if and .Values.clustering.ingestion.enabled .Values.clustering.ingestion.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencti.fullname" . }}-ingestion
  labels:
    {{- include "opencti.ingestionLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opencti.selectorIngestionLabels" . | nindent 6 }}
  {{- if .Values.clustering.ingestion.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.clustering.ingestion.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.clustering.ingestion.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.clustering.ingestion.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
