{{- if not .Values.clustering.enabled }}
{{- include "opencti.serviceTemplate" (merge (dict "serverType" "server" "serviceConfig" .Values.service) .) }}
{{- else }}
{{- if .Values.clustering.frontend.enabled }}
---
{{ include "opencti.serviceTemplate" (merge (dict "serverType" "frontend" "serviceConfig" .Values.clustering.frontend.service) .) }}
{{- end }}
{{- if .Values.clustering.ingestion.enabled }}
---
{{ include "opencti.serviceTemplate" (merge (dict "serverType" "ingestion" "serviceConfig" .Values.clustering.ingestion.service) .) }}
{{- end }}
{{- end }}
