{{- $connectorsGlobal := .Values.connectorsGlobal }}
{{- $serviceType := .Values.service.type }}

{{- range .Values.connectors }}
{{- $connectorName := .name }}
{{- if and .enabled .env.CONNECTOR_EXPOSE_METRICS }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $connectorName }}-service-{{ include "opencti.fullname" $ }}
  labels:
    opencti.connector: {{ $connectorName }}
    {{- include "opencti.labels" $ | nindent 4 }}
spec:
  type: {{ $serviceType }}
  ports:
    {{- if .env.CONNECTOR_EXPOSE_METRICS }}
    - name: metrics
      port: {{ .env.CONNECTOR_METRICS_PORT | default 9095 }}
      targetPort: {{ .env.CONNECTOR_METRICS_PORT | default 9095 }}
      protocol: TCP
    {{- end }}
  selector:
    opencti.connector: {{ $connectorName }}
    {{- include "opencti.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
