{{- range .Values.connectors }}
{{- $connectorName := .name }}
{{ if and .serviceAccount (hasKey .serviceAccount "create") }}
{{- if .serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if and .serviceAccount (hasKey .serviceAccount "name") }}{{ .serviceAccount.name }}{{ else }}{{ include "opencti.fullname" $ }}-{{ $connectorName }}-connector{{ end }}
  labels:
    opencti.connector: {{ $connectorName }}
    {{- include "opencti.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken | default "false" }}
{{- end }}
{{- end }}

{{- end }}
