{{- if .Values.env.APP__TELEMETRY__METRICS__ENABLED }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencti.fullname" . }}-worker
  labels:
    {{- include "opencti.workerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  {{- if eq .Values.worker.service.type "ClusterIP" }}
  clusterIP: {{ .Values.worker.service.clusterIP }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.env.WORKER_PROMETHEUS_TELEMETRY_PORT | default 14269 }}
      targetPort: {{ .Values.env.WORKER_PROMETHEUS_TELEMETRY_PORT | default 14269 }}
      protocol: TCP
  selector:
    {{- include "opencti.selectorWorkerLabels" . | nindent 4 }}
{{- end }}
