{{- if eq .Values.deploymentType "clustering" }}
{{- if .Values.clustering.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencti.fullname" . }}-frontend
  labels:
    {{- include "opencti.frontendLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opencti.selectorFrontendLabels" . | nindent 6 }}
  {{- if .Values.clustering.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.clustering.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.clustering.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.clustering.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
